### ISSUE TITLE
displaying

### ISSUE THREAD

**Issue by paulle** [dmashuda/networkScanner#3]
Thank you for your nice app. Works well, only displaying is not perfect (al least omy phone, xperia z1compact running cm11). See screenshot.
![screenshot_2014-11-25-17-54-41](https://cloud.githubusercontent.com/assets/4852079/5187868/8becf8e0-74d0-11e4-9736-199cab37f3b7.png)

**Comment by dmashuda** [comment]
I Think that i have fixed this issue.  I have published a new version to the play store. If it does not fix the layout on your device, let me know and reopen this issue
